import pandas as pd
calls = pd.read_csv("sales_calls.csv")
revenue = pd.read_csv("sales_revenue.csv")
#print(calls)
#print(revenue)
calls_revenue = pd.merge(calls,revenue,on=['Territory','Month'])
#print(calls_revenue)
#print(calls_revenue[calls_revenue.Territory==3])
#print(calls_revenue[(calls_revenue.Amount/calls_revenue.Calls)>500])
calls_revenue['Call_Amount'] = calls_revenue.Amount/calls_revenue.Calls
#print(calls_revenue)
#print(calls_revenue.Calls.sum())
#print(calls_revenue.Calls.mean())
#print(calls_revenue.Calls.median())
#print(calls_revenue.Calls.min())
#print(calls_revenue.Calls.max())
print(calls_revenue[["Month","Calls","Amount"]].groupby("Month").sum())
print(calls_revenue[["Territory","Calls","Amount"]].groupby("Territory").sum())
import matplotlib
print(print(calls_revenue[["Territory","Calls","Amount"]].groupby("Territory").mean().plot.bar()))